# Generated by Django 5.2.8 on 2026-01-03 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('type_evenement', models.CharField(choices=[('forum', 'Forum Mwasi Mwinda'), ('conference', 'Conférence'), ('atelier', 'Atelier'), ('seminaire', 'Séminaire'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('description_courte', models.TextField(blank=True, help_text='Description courte pour les listes', max_length=500)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(max_length=200)),
                ('adresse_complete', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix en francs congolais', max_digits=10)),
                ('places_disponibles', models.IntegerField(default=0, help_text='0 = illimité')),
                ('places_reservees', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='a_venir', max_length=20)),
                ('publie', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='GalerieEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/galerie/')),
                ('video', models.FileField(blank=True, null=True, upload_to='evenements/galerie/videos/')),
                ('video_url', models.URLField(blank=True, help_text='URL YouTube, Vimeo, etc.')),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='events.evenement')),
            ],
            options={
                'verbose_name': 'Média de galerie',
                'verbose_name_plural': "Galerie d'événements",
                'ordering': ['evenement', 'ordre_affichage', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles')),
                ('present', models.BooleanField(default=False, help_text="Présent à l'événement")),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='events.evenement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('utilisateur', 'evenement')},
            },
        ),
    ]
