# Generated by Django 5.2.8 on 2026-01-05 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerieevenement',
            name='pour_carrousel',
            field=models.BooleanField(default=False, help_text="Cocher pour afficher cette image dans le carrousel de la page d'accueil"),
        ),
        migrations.AlterField(
            model_name='galerieevenement',
            name='evenement',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour les images du carrousel', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='events.evenement'),
        ),
    ]
