# Generated by Django 5.2.8 on 2026-01-03 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='emissions/videos/')),
                ('video_url', models.URLField(blank=True, help_text='URL YouTube, Vimeo, etc.')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='emissions/thumbnails/')),
                ('date_diffusion', models.DateField()),
                ('duree', models.CharField(blank=True, help_text='Ex: 45 min', max_length=20)),
                ('invite', models.CharField(blank=True, help_text="Nom de l'invité(e)", max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=500)),
                ('vues', models.IntegerField(default=0)),
                ('publie', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Émission',
                'verbose_name_plural': 'Émissions',
                'ordering': ['-date_diffusion', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ArticleEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='emissions/articles/')),
                ('publie', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='media_app.emission')),
            ],
            options={
                'verbose_name': "Article d'émission",
                'verbose_name_plural': "Articles d'émission",
                'ordering': ['-date_creation'],
            },
        ),
    ]
