# Generated by Django 5.2.8 on 2026-01-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('fonction', models.CharField(max_length=150)),
                ('biographie', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipe/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('ordre_affichage', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = en premier)")),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MessageDirectrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Mot de la Directrice Générale', max_length=200)),
                ('contenu', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='directrice/')),
                ('signature', models.CharField(default='Nadine Pulumba', max_length=200)),
                ('fonction', models.CharField(default='Directrice Générale', max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Message de la Directrice',
                'verbose_name_plural': 'Messages de la Directrice',
            },
        ),
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vision', 'Vision'), ('mission', 'Mission'), ('valeur', 'Valeur')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icone', models.CharField(blank=True, help_text="Classe CSS pour l'icône (ex: fa-heart)", max_length=100)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vision/Mission/Valeur',
                'verbose_name_plural': 'Vision/Mission/Valeurs',
                'ordering': ['type', 'ordre_affichage'],
            },
        ),
    ]
