# Generated by Django 5.2.8 on 2026-01-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du logo (ex: Logo principal LIKITA)', max_length=200)),
                ('type_logo', models.CharField(choices=[('principal', 'Logo Principal'), ('footer', 'Logo Footer'), ('favicon', 'Favicon'), ('white', 'Logo Blanc'), ('dark', 'Logo Sombre'), ('autre', 'Autre')], default='principal', help_text="Type d'utilisation du logo", max_length=20)),
                ('fichier', models.ImageField(help_text='Image du logo (PNG recommandé avec fond transparent)', upload_to='logos/')),
                ('description', models.TextField(blank=True, help_text='Description du logo')),
                ('actif', models.BooleanField(default=True, help_text='Logo actif (sera utilisé sur le site)')),
                ('ordre_affichage', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = en premier)")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
                'ordering': ['type_logo', 'ordre_affichage', 'nom'],
            },
        ),
    ]
