# Generated by Django 5.2.8 on 2026-01-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedirectrice',
            name='biographie_complete',
            field=models.TextField(blank=True, help_text='Biographie complète de la directrice'),
        ),
        migrations.AddField(
            model_name='messagedirectrice',
            name='competences',
            field=models.TextField(blank=True, help_text='Compétences et expériences professionnelles'),
        ),
        migrations.AddField(
            model_name='messagedirectrice',
            name='engagement_communautaire',
            field=models.TextField(blank=True, help_text='Engagement communautaire et initiatives'),
        ),
        migrations.AddField(
            model_name='messagedirectrice',
            name='formation',
            field=models.TextField(blank=True, help_text='Formation académique'),
        ),
    ]
