# Generated by Django 5.2.8 on 2026-01-03 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('theme', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('description_courte', models.TextField(blank=True, max_length=500)),
                ('type_formation', models.CharField(choices=[('formation', 'Formation'), ('webinaire', 'Webinaire'), ('cours', 'Cours en ligne'), ('atelier', 'Atelier')], default='formation', max_length=20)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('tous', 'Tous niveaux')], default='tous', max_length=20)),
                ('duree', models.CharField(help_text='Ex: 2 jours, 3 semaines, 20 heures', max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix en francs congolais', max_digits=10)),
                ('certificat', models.BooleanField(default=False, help_text='Délivre un certificat à la fin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/')),
                ('formateur', models.CharField(blank=True, max_length=200)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('places_disponibles', models.IntegerField(default=0, help_text='0 = illimité')),
                ('places_reservees', models.IntegerField(default=0)),
                ('publie', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('present', models.BooleanField(default=False, help_text='A suivi la formation')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academia.formation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_formation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription Formation',
                'verbose_name_plural': 'Inscriptions Formations',
                'ordering': ['-date_inscription'],
                'unique_together': {('utilisateur', 'formation')},
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificat', models.CharField(max_length=100, unique=True)),
                ('date_delivrance', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='certificats/')),
                ('verifie', models.BooleanField(default=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='academia.inscriptionformation')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-date_delivrance'],
            },
        ),
    ]
